version: '3.7' 
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11 
    ports: 
      - "8080:8080"
    restart: always

  sonarqube:
    image: sonarqube
    platform: linux/x86_64
    ports: 
      - "9000:9000"
